#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOnline_Server
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="CRMOnline")]
	public partial class CRMOnlineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CRMOnlineDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRMOnlineConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CRMOnlineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CRMOnlineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CRMOnlineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CRMOnlineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user_access> user_accesses
		{
			get
			{
				return this.GetTable<user_access>();
			}
		}
	}
	
	[Table(Name="dbo.user_access")]
	public partial class user_access
	{
		
		private string _user_id;
		
		private string _user_pass;
		
		private System.Nullable<System.Guid> _session_guid;
		
		private System.Nullable<System.DateTime> _last_access_datetime;
		
		public user_access()
		{
		}
		
		[Column(Storage="_user_id", DbType="VarChar(255)")]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[Column(Storage="_user_pass", DbType="VarChar(255)")]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this._user_pass = value;
				}
			}
		}
		
		[Column(Storage="_session_guid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> session_guid
		{
			get
			{
				return this._session_guid;
			}
			set
			{
				if ((this._session_guid != value))
				{
					this._session_guid = value;
				}
			}
		}
		
		[Column(Storage="_last_access_datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_access_datetime
		{
			get
			{
				return this._last_access_datetime;
			}
			set
			{
				if ((this._last_access_datetime != value))
				{
					this._last_access_datetime = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
